### PR TITLE
Add support for Destiny Entity 

### PR DESCRIPTION
**Pull request by aescolastico**
The why of this PR: This is a super useful endpoint for returning manifest data without having to work with the sqlite database, so I added a method to invoke it. 

Thanks

### CODE REVIEW

**Comment by jgayfer** [comment]
Thank you for the PR!

Any chance you could add some of that description to the README, where the other public methods are documented? Realistically the docs should be generated from nice comments like yours, but that's not setup currently :)

**Comment by aescolastico** [comment]
> Thank you for the PR!
> 
> Any chance you could add some of that description to the README, where the other public methods are documented? Realistically the docs should be generated from nice comments like yours, but that's not setup currently :)

Absolutely, I’ll add another commit here soon and reply back for your review.

**Comment by aescolastico** [comment]
@jgayfer Sorry, forgot about this for a sec. Readme entry has been added.

**Comment by aescolastico** [comment]
kindly pinging @jgayfer for review

**Review by jgayfer — APPROVED** [review]
Thanks!

**Comment by jgayfer** [comment]
@aescolastico Published in https://github.com/jgayfer/pydest/releases/tag/0.5.0

**Pull request merged**
